### ISSUE TITLE
MacOS: Investigate warning reported when starting app

### ISSUE THREAD

**Issue by neomatrix369** [julianghionoiu/record-and-upload#12]
While working on #6, the below warning occurred:

```
<snipped>
x record/Contents/MacOS/record-and-upload
INFO  [main]       - Starting recording app
INFO  [main]       - Checking permissions
INFO  [main]       - Logging initialized @2559ms to org.eclipse.jetty.util.log.Slf4jLog
INFO  [VideoRec]   - Open the input stream
WARN  [main]       - Cannot run program "git" (in directory "/usr/bin"): error=2, No such file or directory  <==== this one
INFO  [Upload]     - Sync local files with remote
```

Not clear what the cause could be as on manually checking git does exists in `/usr/bin` and also running git n the CLI does give a response.

Theory: if any of the direct or transient dependencies are actually looking to talk to `/usr/bin/git`? There could be an issue there, if they did and the OS wasn't allowing access to it.

**Comment by neomatrix369** [comment]
Will look at it as part of the package creation end-to-end pipeline task

**Comment by neomatrix369** [comment]
```
Here's the exanded snippet of the logs 
[---snipped---]
o.eclipse.jetty.util.component.ContainerLifeCycle [39mDEBUG [main]      [0;39m - org.eclipse.jetty.servlet.ServletHandler@41709512 added {[/stop]=>tdl.record_upload.events.ExternalEventServerThread$PostEventServlet-388526fb,POJO}
org.eclipse.jgit.util.FS [39mDEBUG [main]      [0;39m - readpipe [git, --version],/usr/bin
org.eclipse.jgit.util.FS [31mWARN  [main]      [0;39m - Cannot run program "git" (in directory "/usr/bin"): error=2, No such file or directory
t.record_upload.upload.BackgroundRemoteSyncTask$1 [1;30mINFO  [Upload]    [0;39m - Sync local files with remote
org.eclipse.jetty.util.component.AbstractLifeCycle [39mDEBUG [main]      [0;39m - starting org.eclipse.jetty.server.Server@2c07545f
tdl.record_upload.MetricsReportingTask [1;30mINFO  [Metrics]   [0;39m - tick   1, video recoding disabled
[--snipped--]
```

I have narrowed it down to this line in JGit: https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/util/FS.java#L688

It might not be an issue, as I see the below when I change the source files:

```
INFO  [Upload]     - Uploading file /path/to/tdl-runner-java/record/localstore/sourcecode_20181211T173904.srcs
INFO  [SourceRec]  - Start recording to "sourcecode_20181211T173904.srcs"
INFO  [Upload]     - Finished uploading file /path/to/tdl-runner-java/record/localstore/sourcecode_20181211T173904.srcs
INFO  [Upload]     - Uploading file /path/to/tdl-runner-java/record/localstore/record-and-upload-20181211T173803.log
INFO  [Upload]     - Finished uploading file /path/to/tdl-runner-java/record/localstore/record-and-upload-20181211T173803.log
INFO  [Upload]     - Uploading file /path/to/tdl-runner-java/record/localstore/record-and-upload-20181211T173902.log
INFO  [Upload]     - Finished uploading file /path/to/tdl-runner-java/record/localstore/record-and-upload-20181211T173902.log
INFO  [Upload]     - Uploading file /path/to/tdl-runner-java/record/localstore/sourcecode_20181211T173805.srcs
INFO  [Upload]     - Finished uploading file /path/to/tdl-runner-java/record/localstore/sourcecode_20181211T173805.srcs
<snipped>
INFO  [Metrics]    - tick  17, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  18, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  19, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  20, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  21, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  22, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  23, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  24, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  25, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  26, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  27, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  28, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  29, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  30, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  31, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  32, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  33, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  34, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  35, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  36, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  37, video recoding disabled |  1 source capture, 70959 ms/capture
INFO  [Metrics]    - tick  38, video recoding disabled |  1 source capture, 70959 ms/capture
INFO  [Metrics]    - tick  39, video recoding disabled |  1 source capture, 70959 ms/capture
INFO  [Metrics]    - tick  40, video recoding disabled |  1 source capture, 70959 ms/capture
INFO  [Metrics]    - tick  41, video recoding disabled |  1 source capture, 70959 ms/capture
INFO  [Metrics]    - tick  42, video recoding disabled |  1 source capture, 70959 ms/capture
INFO  [Metrics]    - tick  43, video recoding disabled |  1 source capture, 70959 ms/capture
INFO  [Metrics]    - tick  44, video recoding disabled |  1 source capture, 70959 ms/capture
[snipped]
INFO  [Metrics]    - Uploaded 0.6% of 102.86 MB at 0.747 MB/sec
INFO  [Metrics]    - Uploaded 9.7% of 102.86 MB at 3.578 MB/sec
INFO  [Metrics]    - Uploaded 19.4% of 102.86 MB at 4.250 MB/sec
INFO  [Metrics]    - Uploaded 27.8% of 102.86 MB at 4.319 MB/sec
INFO  [Metrics]    - Uploaded 36.1% of 102.86 MB at 4.349 MB/sec
INFO  [Metrics]    - Uploaded 42.1% of 102.86 MB at 4.154 MB/sec
INFO  [Metrics]    - Uploaded 50.1% of 102.86 MB at 4.178 MB/sec
INFO  [Metrics]    - Uploaded 58.1% of 102.86 MB at 4.189 MB/sec
INFO  [Metrics]    - Uploaded 66.8% of 102.86 MB at 4.252 MB/sec
INFO  [Metrics]    - Uploaded 74.7% of 102.86 MB at 4.249 MB/sec
INFO  [Metrics]    - Uploaded 80.5% of 102.86 MB at 4.144 MB/sec
INFO  [Metrics]    - Uploaded 85.1% of 102.86 MB at 3.999 MB/sec
INFO  [Metrics]    - Uploaded 89.9% of 102.86 MB at 3.884 MB/sec
INFO  [Metrics]    - Uploaded 94.5% of 102.86 MB at 3.782 MB/sec
INFO  [Metrics]    - Uploaded 99.1% of 102.86 MB at 3.692 MB/sec
INFO  [main]       - Finished uploading file /Users/swami/git-repos/BeFaster/tdl-runner-java/record/localstore/sourcecode_20181211T173904.srcs
INFO  [main]       - Uploading file /Users/swami/git-repos/BeFaster/tdl-runner-java/record/localstore/record-and-upload-20181211T173902.log
INFO  [main]       - Finished uploading file /Users/swami/git-repos/BeFaster/tdl-runner-java/record/localstore/record-and-upload-20181211T173902.log
INFO  [main]       - ~~~~~~ Stopped ~~~~~~
```

We see from both the code and the log messages its a warning rather than an error - and this commit explains further that there is a check then to see if its not calling an incorrect git cli, see https://github.com/eclipse/jgit/commit/8a53d7e2fd5b84c57c08ec3912ed61612edb7cb9

I dont think it might be an issue.

**Comment by neomatrix369** [comment]
Let me know what you like to do about it?

**Comment by julianghionoiu** [comment]
I would like us to try running this on a system without Git installed, like a container. It should still work.

**Comment by neomatrix369** [comment]
I ran it in the container and this is how it was in `--no-video` mode:
```
root@74040d78818d:/record-linux-packr# ./record/record-and-upload --config $(pwd)/config/credentials.config --store $(pwd)/localstore --no-video
INFO  [main]       - Starting recording app
INFO  [main]       - Checking permissions
INFO  [main]       - Logging initialized @1176ms to org.eclipse.jetty.util.log.Slf4jLog
INFO  [Upload]     - Sync local files with remote
INFO  [Metrics]    - tick   1, video recoding disabled
INFO  [main]       - jetty-9.4.z-SNAPSHOT
INFO  [main]       - Started ServerConnector@57abad67{HTTP/1.1,[http/1.1]}{localhost:41375}
INFO  [main]       - Started @1287ms
INFO  [SourceRec]  - Start recording to "sourcecode_20181212T150757.srcs"
INFO  [Upload]     - Uploading file /record-linux-packr/localstore/record-and-upload-20181212T150757.log
INFO  [Upload]     - Finished uploading file /record-linux-packr/localstore/record-and-upload-20181212T150757.log
INFO  [Upload]     - Uploading file /record-linux-packr/localstore/sourcecode_20181212T150537.srcs
INFO  [Upload]     - Finished uploading file /record-linux-packr/localstore/sourcecode_20181212T150537.srcs
INFO  [Upload]     - Uploading file /record-linux-packr/localstore/record-and-upload-20181212T150536.log
INFO  [Upload]     - Finished uploading file /record-linux-packr/localstore/record-and-upload-20181212T150536.log
INFO  [Upload]     - Uploading file /record-linux-packr/localstore/sourcecode_20181212T150757.srcs
INFO  [Upload]     - Finished uploading file /record-linux-packr/localstore/sourcecode_20181212T150757.srcs
INFO  [Metrics]    - tick   2, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick   3, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick   4, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick   5, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick   6, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick   7, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick   8, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick   9, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  10, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  11, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  12, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  13, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  14, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  15, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  16, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  17, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  18, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  19, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  20, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  21, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  22, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  23, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  24, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  25, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  26, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  27, video recoding disabled |  0 source capture,   0 ms/capture
INFO  [Metrics]    - tick  28, video recoding disabled |  1 source capture, 52972 ms/capture
INFO  [Metrics]    - tick  29, video recoding disabled |  1 source capture, 52972 ms/capture
INFO  [Metrics]    - tick  30, video recoding disabled |  1 source capture, 52972 ms/capture
```

**Comment by neomatrix369** [comment]
I ran it in the container and this is how it was in video recording mode:

```java
root@aeeeb0a3928c:/record-linux-packr# ./record/record-and-upload --config $(pwd)/config/credentials.config --store $(pwd)/localstore
INFO  [main]       - Starting recording app
INFO  [main]       - Checking permissions
INFO  [main]       - Logging initialized @1184ms to org.eclipse.jetty.util.log.Slf4jLog
Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /record-linux-packr/record/libhumblevideo.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
INFO  [VideoRec]   - Open the input stream
ERROR [VideoRec]   - Video recorder encountered exception. Recording has been stopped.
tdl.record.screen.video.VideoRecorderException: Could not open input source
	at tdl.record.screen.video.VideoRecorder.open(VideoRecorder.java:99) ~[record-and-upload-v0.0.16.jar:na]
	at tdl.record_upload.video.VideoRecordingThread.run(VideoRecordingThread.java:35) ~[record-and-upload-v0.0.16.jar:na]
Caused by: tdl.record.screen.image.input.InputImageGenerationException: java.awt.AWTException: headless environment
	at tdl.record.screen.image.input.InputFromScreen.open(InputFromScreen.java:29) ~[record-and-upload-v0.0.16.jar:na]
	at tdl.record.screen.image.input.ScaleToOptimalSizeImage.open(ScaleToOptimalSizeImage.java:26) ~[record-and-upload-v0.0.16.jar:na]
	at tdl.record.screen.video.VideoRecorder.open(VideoRecorder.java:97) ~[record-and-upload-v0.0.16.jar:na]
	... 1 common frames omitted
Caused by: java.awt.AWTException: headless environment
	at java.awt.Robot.<init>(Robot.java:91) ~[na:1.8.0_172]
	at tdl.record.screen.image.input.InputFromScreen.open(InputFromScreen.java:23) ~[record-and-upload-v0.0.16.jar:na]
	... 3 common frames omitted
INFO  [Upload]     - Sync local files with remote
INFO  [main]       - jetty-9.4.z-SNAPSHOT
INFO  [main]       - Started ServerConnector@6c45ee6e{HTTP/1.1,[http/1.1]}{localhost:41375}
INFO  [main]       - Started @1307ms
INFO  [SourceRec]  - Start recording to "sourcecode_20181212T151608.srcs"
INFO  [Upload]     - Uploading file /record-linux-packr/localstore/record-and-upload-20181121T010045.log
INFO  [Upload]     - Finished uploading file /record-linux-packr/localstore/record-and-upload-20181121T010045.log
INFO  [Upload]     - Uploading file /record-linux-packr/localstore/record-and-upload-20181212T151607.log
INFO  [Upload]     - Finished uploading file /record-linux-packr/localstore/record-and-upload-20181212T151607.log
INFO  [Upload]     - Uploading file /record-linux-packr/localstore/record-and-upload-20181121T010925.log
INFO  [Upload]     - Finished uploading file /record-linux-packr/localstore/record-and-upload-20181121T010925.log
INFO  [Upload]     - Uploading file /record-linux-packr/localstore/sourcecode_20181121T012838.srcs
INFO  [Upload]     - Finished uploading file /record-linux-packr/localstore/sourcecode_20181121T012838.srcs
INFO  [Upload]     - Uploading file /record-linux-packr/localstore/record-and-upload-20181121T012548.log
INFO  [Upload]     - Finished uploading file /record-linux-packr/localstore/record-and-upload-20181121T012548.log
INFO  [Upload]     - Uploading file /record-linux-packr/localstore/record-and-upload-20181121T010619.log
INFO  [Upload]     - Finished uploading file /record-linux-packr/localstore/record-and-upload-20181121T010619.log
INFO  [Upload]     - Uploading file /record-linux-packr/localstore/record-and-upload-20181121T014006.log
INFO  [Upload]     - Finished uploading file /record-linux-packr/localstore/record-and-upload-20181121T014006.log
INFO  [Upload]     - Uploading file /record-linux-packr/localstore/sourcecode_20181121T010721.srcs
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 0.0% of 143.30 MB at 0.000 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 1.7% of 143.30 MB at 1.008 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 3.0% of 143.30 MB at 1.017 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 4.4% of 143.30 MB at 1.028 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 5.9% of 143.30 MB at 1.036 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 7.0% of 143.30 MB at 0.998 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 8.3% of 143.30 MB at 0.998 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 9.5% of 143.30 MB at 0.984 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 10.5% of 143.30 MB at 0.953 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 12.2% of 143.30 MB at 0.987 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 13.5% of 143.30 MB at 0.990 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 15.0% of 143.30 MB at 0.999 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 16.4% of 143.30 MB at 1.004 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 17.4% of 143.30 MB at 0.989 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 19.1% of 143.30 MB at 1.008 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 20.5% of 143.30 MB at 1.009 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 21.9% of 143.30 MB at 1.012 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 23.3% of 143.30 MB at 1.013 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 24.4% of 143.30 MB at 1.005 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 26.1% of 143.30 MB at 1.019 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 27.5% of 143.30 MB at 1.020 MB/sec
```

The only message that came up while running it inside docker was:
```java
ERROR [VideoRec]   - Video recorder encountered exception. Recording has been stopped.
tdl.record.screen.video.VideoRecorderException: Could not open input source
	at tdl.record.screen.video.VideoRecorder.open(VideoRecorder.java:99) ~[record-and-upload-v0.0.16.jar:na]
	at tdl.record_upload.video.VideoRecordingThread.run(VideoRecordingThread.java:35) ~[record-and-upload-v0.0.16.jar:na]
Caused by: tdl.record.screen.image.input.InputImageGenerationException: java.awt.AWTException: headless environment
	at tdl.record.screen.image.input.InputFromScreen.open(InputFromScreen.java:29) ~[record-and-upload-v0.0.16.jar:na]
	at tdl.record.screen.image.input.ScaleToOptimalSizeImage.open(ScaleToOptimalSizeImage.java:26) ~[record-and-upload-v0.0.16.jar:na]
	at tdl.record.screen.video.VideoRecorder.open(VideoRecorder.java:97) ~[record-and-upload-v0.0.16.jar:na]
	... 1 common frames omitted
Caused by: java.awt.AWTException: headless environment
	at java.awt.Robot.<init>(Robot.java:91) ~[na:1.8.0_172]
	at tdl.record.screen.image.input.InputFromScreen.open(InputFromScreen.java:23) ~[record-and-upload-v0.0.16.jar:na]
	... 3 common frames omitted
```
But that could be due to not able to find the file in the video file docker environment, because running it in the native environment gave me this:

```
 ./record/record-and-upload --config $(pwd)/config/credentials.config --store $(pwd)/localstore 
INFO  [main]       - Starting recording app
INFO  [main]       - Checking permissions
INFO  [main]       - Logging initialized @1176ms to org.eclipse.jetty.util.log.Slf4jLog
Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /path/to/tdl-runner-java/record/libhumblevideo.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
INFO  [VideoRec]   - Open the input stream
INFO  [Upload]     - Sync local files with remote
INFO  [main]       - jetty-9.4.z-SNAPSHOT
INFO  [main]       - Started ServerConnector@1b765a2c{HTTP/1.1,[http/1.1]}{localhost:41375}
INFO  [main]       - Started @1289ms
INFO  [VideoRec]   - Start recording to "screencast_20181212T151827.mp4" at 16 fps with 4 screenshots/sec
INFO  [SourceRec]  - Start recording to "sourcecode_20181212T151827.srcs"
INFO  [Upload]     - Uploading file /path/to/tdl-runner-java/localstore/record-and-upload-20181212T151607.log
INFO  [Upload]     - Finished uploading file /path/to/tdl-runner-java/localstore/record-and-upload-20181212T151607.log
INFO  [Upload]     - Uploading file /path/to/tdl-runner-java/localstore/record-and-upload-20181212T151826.log
INFO  [Upload]     - Finished uploading file /path/to/tdl-runner-java/localstore/record-and-upload-20181212T151826.log
INFO  [Upload]     - Uploading file /path/to/tdl-runner-java/localstore/sourcecode_20181121T010721.srcs
INFO  [Metrics]    - Recorded 0h00m01s,   6 frames, 0.00 MB |  0 source capture,   0 ms/capture | Uploaded 67.3% of 143.30 MB at 72.362 MB/sec
^CWARN  [Shutdown]   - Shutdown signal received
INFO  [Shutdown]   - Stopping recording
INFO  [Shutdown]   - Stopping recording
INFO  [VideoRec]   - Flushing remaining frames
INFO  [VideoRec]   - Recording stopped
INFO  [VideoRec]   - Closing the video stream
^CINFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 68.7% of 143.30 MB at 30.392 MB/sec
^CINFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 70.1% of 143.30 MB at 19.510 MB/sec
^CINFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 71.5% of 143.30 MB at 14.531 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 73.0% of 143.30 MB at 11.666 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 74.4% of 143.30 MB at 9.807 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 75.7% of 143.30 MB at 8.490 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 77.1% of 143.30 MB at 7.526 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 78.5% of 143.30 MB at 6.782 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 79.9% of 143.30 MB at 6.193 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 81.4% of 143.30 MB at 5.713 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 82.8% of 143.30 MB at 5.315 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 83.7% of 143.30 MB at 4.954 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 85.3% of 143.30 MB at 4.677 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 86.8% of 143.30 MB at 4.439 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 88.1% of 143.30 MB at 4.218 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 89.7% of 143.30 MB at 4.036 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 90.7% of 143.30 MB at 3.851 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 92.6% of 143.30 MB at 3.719 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 93.8% of 143.30 MB at 3.579 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 95.1% of 143.30 MB at 3.453 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 96.7% of 143.30 MB at 3.348 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 97.7% of 143.30 MB at 3.233 MB/sec
INFO  [Metrics]    -  0 source capture,   0 ms/capture | Uploaded 99.5% of 143.30 MB at 3.156 MB/sec
```

I looked into the code for the error, it came from the below block of code in `/dev-screen-record-0.0.6-sources.jar!/tdl/record/screen/video/VideoRecorder.java`:

```java
        log.info("Open the input stream");
        try {
            imageInput.open();
        } catch (InputImageGenerationException e) {
            throw new VideoRecorderException("Could not open input source", e);
        }
```
On a side note it would help if the name of the file it couldn't find was shown, where does it try to create the file or look for the input file?

**Comment by neomatrix369** [comment]
One more thing which I had never seen in the logs:
```
Logging initialized @1176ms to org.eclipse.jetty.util.log.Slf4jLog
Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /path/to/tdl-runner-java/record/libhumblevideo.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
```
I haven't see the same message for MacOS and Windows versions.

**Comment by neomatrix369** [comment]
I think from the above, we are safe using the record-and-save in clean environments with the absence of git, but I would still like to know my query about the input source, its something I don't provide via CLI args.

**Comment by neomatrix369** [comment]
@julianghionoiu should we close this issue now?
